name: flame_3d_testbed
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: 1.7.3
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 0.2.0+2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/objs/